CREATE TABLE IF NOT EXISTS plans(
 	id int UNSIGNED NOT NULL AUTO_INCREMENT,
	plan VARCHAR(100) NOT NULL,
    period_plan ENUM('7', '30','90') NOT NULL,
    price INT UNSIGNED NOT NULL,
    
    PRIMARY KEY (id)
) AUTO_INCREMENT = 10